#Credits to my friend for making this file!
print ("\033[1;34;40m Welcome to chatbot \n")
name = input("What is your name? ")
print ("Hello "+name)
age = int(input("How old are you? "))
color = input("What is your favourite color? ")
print (color+" is my favourite color too!")
input("In which country do you live? ")
vacation = input("Where would you like to go for vacation? ")
print ("I would also like to visit "+vacation)
thing = input("What is the first thing you would do when you go on vacation? ")
print ("I would also like to "+thing+ " when I go on vacation")
car = input("Which car do you/your parents own? ")
dream = input("What is your dream car? ")
print ("I would also like to own a "+dream)
house = input("What is your dream house? ")
print ("I would also like to live in "+house)
input("Which is your favourite country? ")
friend = input("Who is your best friend? ")
print ("I have a good feeling about "+friend)
input("Would you be my friend? ")
print ("Ok, I will see you soon!")
print ("Goodbye!")
